#!/bin/sh
cd "${0%/*}" || exit    # Run from this directory
#------------------------------------------------------------------------------

wclean libso laserDTRM
wclean libso phasesSystem
# ./WENOEXT/Allwclean
./THERMORAY/Allwclean
wclean

#------------------------------------------------------------------------------
